#!/usr/bin/env perl
## cobalt2/Install
## Simplistic cobalt2 "installer" walkthru

use 5.12.1;
use strict;
use warnings;

use File::Spec;
use File::Basename;
my(@root, $tools, $etc, $lib);
BEGIN {
 @root  = File::Spec->splitdir(dirname(__FILE__));
 $tools = File::Spec->rel2abs(join '/', @root, 'tools');
 $etc   = File::Spec->rel2abs(join '/', @root, 'etc');
 $lib   = File::Spec->rel2abs(join '/', @root, 'lib');
}
use lib $lib;

my @confs = qw{ cobalt.conf auth.conf channels.conf plugins.conf };

sub _ans {
  my ($stdin, $default) = @_;
  chomp($stdin);
  $stdin = $stdin ? $stdin : $default ;
  return unless $stdin =~ /^Y/i;
}


say "> Welcome to cobalt2!";

print "> Should I attempt to check module dependencies? [Y/n] ";
if ( _ans(my $stdin = <STDIN>, 'y') ) {
  unless (-f qq{$tools/test_deps}) {
    say ">! Can't find test_deps: $tools/test_deps";
    die
  } else {
    say "> Executing test_deps, one moment . . .";
    system(qq{$tools/test_deps});
    say "> Dependency check finished.\n";
  }
} else {
  say ">! Skipping dependency check . . .\n";
}


say "> These are the core conf files:";
print "  * $_\n" for @confs;
print "> Would you like to edit them now? [Y/n] ";
if ( _ans(my $stdin = <STDIN>, 'y') ) {
  my $editor;
  unless ($ENV{EDITOR}) {
    say ">! You don't seem to have EDITOR set.";
    say ">! You can enter one here, or press enter to skip.";
    say "> Edit with: ";
    $editor = <STDIN> ; chomp($editor);
  } else { $editor = $ENV{EDITOR}; }

  if ($editor) {
    for my $file (@confs) {
      if (basename($file, '.conf', '.yml') eq 'auth') {
        say "> Auth plugin confs may include user directives with hashed"
            ." passwords.";
        say "> Typically hashed passwords can be created via tools/mkpasswd";
        say "> I can do this for you, using Cobalt::Utils and bcrypt.";
        say "> (This, of course, assumes that your kit is complete.)";
        print "> Would you like to generate a hash before editing '$file'? [Y/n] ";
        if ( _ans(my $stdin = <STDIN>, 'y') ) {
          require Term::ReadKey;
          Term::ReadKey->import('ReadMode');
          ReadMode('noecho');
          print "Password: ";
          my $pwd = <STDIN>;
          ReadMode(0);
          require Cobalt::Utils;
          say "\n HASH:\n".Cobalt::Utils::mkpasswd($pwd);
          say "Hit enter when you'd like to continue.";
          <STDIN>;
        }
      }
      say "> Editing $etc/$file";
      system(qq{$editor $etc/$file});
    }
    say "You will probably still want to edit plugin-specific configs.";
    say "The full path to your etc/ is: \n$etc";
  } else {
    say ">! No editor found; skipping configuration files.";
  }

} else {
  say ">! Skipping configuration files.";
}



say "> Finished.";
say "You may want to read the README and ./cobalt --help";
