=pod

=head1 NAME

Cobalt::Plugin::Auth -- standard access control plugin

=head1 DESCRIPTION

This plugin provides the standard authorization and access control 
functionality for B<Cobalt>.

=head1 COMMANDS

=head2 Logging in

=head2 Changing your password

=head2 User administration

=head3 user add

=head3 user del

=head3 user chflags

=head3 user chpass




=head1 CONFIGURATION

=head2 plugins.conf

=head2 auth.conf


=head1 EMITTED EVENTS

=head2 Bot_auth_user_login

=head2 Bot_auth_failed_login

=head2 Bot_auth_user_logout



=head1 ACCEPTED EVENTS

Listens for the following events:

=over

=item *

Bot_connected

=item *

Bot_disconnected

=item *

Bot_private_msg

=item *

Bot_user_left

=item *

Bot_self_left

=item *

Bot_user_kicked

=item *

Bot_self_kicked

=item *

Bot_user_quit

=item *

Bot_nick_changed

=back


=head1 AUTHOR

Jon Portnoy <avenj@cobaltirc.org>

L<http://www.cobaltirc.org>

=cut
