#!/usr/bin/env perl
## Check for cobalt2 dependencies
## Prompt to see if we should try to install them

use 5.12.1;
use strict;
use warnings;

my @missing;
my @required = qw/
    Moose
    MooseX::NonMoose
    namespace::autoclean

    Crypt::Eksblowfish

    File::Slurp

    Log::Handler

    Proc::PID::File

    IRC::Utils
    POE::Component::IRC

    POE::Component::Syndicator

    YAML::Syck
  /;

## bundled plugins, mostly
##  module => reason
my $optional = {
  'DBM::Deep' => 'Used by Plugin::RDB',

  'Term::ReadKey' => 'Used by tools/mkpasswd',
#  'Template' => 'Used by documentation tools'
};

print "> Checking required modules; ".scalar(@required)." to check\n";
my $i;
for my $module (sort @required) {
    ++$i;
    eval "require $module";
    if ($@) {
      push(@missing, $module);
    } else {
      say " ($i) found $module";
    }
}


say "> Checking recommended modules . . .";
for my $module (sort keys %{ $optional }) {
  eval "require $module";
  unless ($@) {
    say " found $module";
    next
  } else {
    print "Missing:\n",
          "$module  --  ".$optional->{$module},
          "\n> Add $module to install list? [Y/n] " ;
    my $yn = <STDIN>; chomp($yn);
    $yn = $yn ? $yn : 'Y' ;
    given ($yn) {
      push(@missing, $module) when /Y(es)?$/i;
      default { say "Skipping $module" ; next }
    }
  }
}

if (@missing) {
  print " !! missing modules:\n",
          join("\n", @missing), "\n";

  my $themit = @missing == 1 ? 'it' : 'them' ;
  print "> Should I try to install $themit via CPANPLUS? [Y/n] ";
  my $yn = <STDIN>;  chomp($yn);
  $yn = 'Y' unless $yn;
  given ($yn)  {
    when (/Y(es)?$/i) {
      say " ... if you've yet to run CPANPLUS, this may take a few ...";
      require CPANPLUS;
      CPANPLUS->import("install");

      my @failed;
      for my $module (@missing) {
        ## double-check to see if we got it in a deptree somewheres:
        eval "require $module";
        if ($@) {
          push(@failed, $module) unless install($module);
        } else { say " found: $module"; }
      }

      if (@failed) {
        say "! Some modules failed to install:";
        print join "\n", @failed, "\n";
      }

    }

    default { 
      say "\nYou may want to install manually via `cpan` or `cpanm` \n";
    }
  }
}

